# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://scan.coverity.com/projects/libgd
name: Coverity Scan

on:
  workflow_call:
    secrets:
      COVERITY_SCAN_EMAIL:
        required: true
      COVERITY_SCAN_TOKEN:
        required: true

permissions: 
  contents: read

jobs:
  coverity:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cc: [gcc]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - name: Update apt
      run: sudo apt-get update -qq
    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          libavifile-0.7-dev \
          libde265-dev \
          libfreetype-dev \
          libheif-dev \
          libimagequant-dev \
          libjpeg-turbo8-dev \
          libpng-dev \
          libraqm-dev \
          libtiff5-dev \
          libwebp-dev \
          libx265-dev \
          libxpm-dev
    - uses: actions/checkout@v5
    - name: Configure gd
      run: |
        cmake \
          -DENABLE_CPP=1 \
          -DENABLE_FREETYPE=1 \
          -DENABLE_GD_FORMATS=1 \
          -DENABLE_HEIF=0 \
          -DENABLE_JPEG=1 \
          -DENABLE_PNG=1 \
          -DENABLE_TIFF=1 \
          -DENABLE_WEBP=1 \
          -DBUILD_TEST=1 \
          -B ${{github.workspace}}/build
    - name: URL encode Coverity project name
      id: project
      run: echo "project=${GITHUB_REPOSITORY}" | sed -e 's:/:%2F:g' -e 's/ /%20/g' >> $GITHUB_OUTPUT

    - name: Lookup Coverity Build Tool hash
      id: coverity-cache-lookup
      run: |
        hash=$(curl https://scan.coverity.com/download/cxx/linux64 \
          --data "token=${TOKEN}&project=${{ steps.project.outputs.project }}&md5=1")
        echo "hash=${hash}" >> $GITHUB_OUTPUT
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

    - name: Cache Coverity Build Tool
      id: cov-build-cache
      uses: actions/cache@v4
      with:
        path: ${{github.workspace}}/cov-analysis
        key: cov-build-cxx-linux64-${{ steps.coverity-cache-lookup.outputs.hash }}

    - name: Download Coverity Build Tool
      if: steps.cov-build-cache.outputs.cache-hit != 'true'
      run: |
        curl https://scan.coverity.com/download/cxx/linux64 \
          --no-progress-meter \
          --output cov-analysis.tar.gz \
          --data "token=${TOKEN}&project=${{ steps.project.outputs.project }}"
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

    - name: Extract Coverity Build Tool
      if: steps.cov-build-cache.outputs.cache-hit != 'true'
      run: |
        mkdir cov-analysis
        tar -xzf cov-analysis.tar.gz --strip 1 -C cov-analysis

    - name: Build with cov-build
      run: |
        export PATH="${PWD}/cov-analysis/bin:${PATH}"
        cov-build --dir cov-int cmake --build ${{github.workspace}}/build

    - name: Archive Coverity results
      run: tar -czf cov-int.tgz cov-int

    - name: Submit results to Coverity Scan
      run: |
        curl \
          --form token="${TOKEN}" \
          --form email="${{ secrets.COVERITY_SCAN_EMAIL }}" \
          --form file=@cov-int.tgz \
          --form version="${{ github.sha }}" \
          --form description="Coverity Scan ${{ github.repository }} / ${{ github.ref }}" \
          "https://scan.coverity.com/builds?project=${{ steps.project.outputs.project }}"
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
